/*
External API

## Date type fields API endpoints expected date in UTC±0:00 timezone. Timezones in ISO8601 format will be ignored. API endpoints support date in two formats (one of): ISO8601 ('YYYY-MM-DDTHH:mm:SSZ') or Unix Timestamp (seconds count since January 1st, 1970 at UTC).  ## Dropdown fields Some fields are configured as dropdown fields with a dedicated list of values within Oomnitza. You can review the list of available dropdown values within the customization page in Oomnitza. In case you want to be able to post any data into these fields, you should switch them to dropdown without value within the customization page. 

API version: 3.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ConnectorRunLogs struct for ConnectorRunLogs
type ConnectorRunLogs struct {
	PortionId int32 `json:"portion_id"`
	PortionCorrelationId string `json:"portion_correlation_id"`
	StartTime float32 `json:"start_time"`
	EndTime float32 `json:"end_time"`
	Connector string `json:"connector"`
	IsMediaStorageService bool `json:"is_media_storage_service"`
	Status string `json:"status"`
	TestRun bool `json:"test_run"`
	Deployment string `json:"deployment"`
	Ipv4Address string `json:"ipv4_address"`
	AddedRecordsCount int32 `json:"added_records_count"`
	UpdatedRecordsCount int32 `json:"updated_records_count"`
	SkippedRecordsCount int32 `json:"skipped_records_count"`
	ErrorLogsCount int32 `json:"error_logs_count"`
}

// NewConnectorRunLogs instantiates a new ConnectorRunLogs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorRunLogs(portionId int32, portionCorrelationId string, startTime float32, endTime float32, connector string, isMediaStorageService bool, status string, testRun bool, deployment string, ipv4Address string, addedRecordsCount int32, updatedRecordsCount int32, skippedRecordsCount int32, errorLogsCount int32) *ConnectorRunLogs {
	this := ConnectorRunLogs{}
	this.PortionId = portionId
	this.PortionCorrelationId = portionCorrelationId
	this.StartTime = startTime
	this.EndTime = endTime
	this.Connector = connector
	this.IsMediaStorageService = isMediaStorageService
	this.Status = status
	this.TestRun = testRun
	this.Deployment = deployment
	this.Ipv4Address = ipv4Address
	this.AddedRecordsCount = addedRecordsCount
	this.UpdatedRecordsCount = updatedRecordsCount
	this.SkippedRecordsCount = skippedRecordsCount
	this.ErrorLogsCount = errorLogsCount
	return &this
}

// NewConnectorRunLogsWithDefaults instantiates a new ConnectorRunLogs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorRunLogsWithDefaults() *ConnectorRunLogs {
	this := ConnectorRunLogs{}
	return &this
}

// GetPortionId returns the PortionId field value
func (o *ConnectorRunLogs) GetPortionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PortionId
}

// GetPortionIdOk returns a tuple with the PortionId field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogs) GetPortionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PortionId, true
}

// SetPortionId sets field value
func (o *ConnectorRunLogs) SetPortionId(v int32) {
	o.PortionId = v
}

// GetPortionCorrelationId returns the PortionCorrelationId field value
func (o *ConnectorRunLogs) GetPortionCorrelationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PortionCorrelationId
}

// GetPortionCorrelationIdOk returns a tuple with the PortionCorrelationId field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogs) GetPortionCorrelationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PortionCorrelationId, true
}

// SetPortionCorrelationId sets field value
func (o *ConnectorRunLogs) SetPortionCorrelationId(v string) {
	o.PortionCorrelationId = v
}

// GetStartTime returns the StartTime field value
func (o *ConnectorRunLogs) GetStartTime() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogs) GetStartTimeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *ConnectorRunLogs) SetStartTime(v float32) {
	o.StartTime = v
}

// GetEndTime returns the EndTime field value
func (o *ConnectorRunLogs) GetEndTime() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogs) GetEndTimeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *ConnectorRunLogs) SetEndTime(v float32) {
	o.EndTime = v
}

// GetConnector returns the Connector field value
func (o *ConnectorRunLogs) GetConnector() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Connector
}

// GetConnectorOk returns a tuple with the Connector field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogs) GetConnectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Connector, true
}

// SetConnector sets field value
func (o *ConnectorRunLogs) SetConnector(v string) {
	o.Connector = v
}

// GetIsMediaStorageService returns the IsMediaStorageService field value
func (o *ConnectorRunLogs) GetIsMediaStorageService() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsMediaStorageService
}

// GetIsMediaStorageServiceOk returns a tuple with the IsMediaStorageService field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogs) GetIsMediaStorageServiceOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsMediaStorageService, true
}

// SetIsMediaStorageService sets field value
func (o *ConnectorRunLogs) SetIsMediaStorageService(v bool) {
	o.IsMediaStorageService = v
}

// GetStatus returns the Status field value
func (o *ConnectorRunLogs) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogs) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ConnectorRunLogs) SetStatus(v string) {
	o.Status = v
}

// GetTestRun returns the TestRun field value
func (o *ConnectorRunLogs) GetTestRun() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TestRun
}

// GetTestRunOk returns a tuple with the TestRun field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogs) GetTestRunOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TestRun, true
}

// SetTestRun sets field value
func (o *ConnectorRunLogs) SetTestRun(v bool) {
	o.TestRun = v
}

// GetDeployment returns the Deployment field value
func (o *ConnectorRunLogs) GetDeployment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Deployment
}

// GetDeploymentOk returns a tuple with the Deployment field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogs) GetDeploymentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deployment, true
}

// SetDeployment sets field value
func (o *ConnectorRunLogs) SetDeployment(v string) {
	o.Deployment = v
}

// GetIpv4Address returns the Ipv4Address field value
func (o *ConnectorRunLogs) GetIpv4Address() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ipv4Address
}

// GetIpv4AddressOk returns a tuple with the Ipv4Address field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogs) GetIpv4AddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ipv4Address, true
}

// SetIpv4Address sets field value
func (o *ConnectorRunLogs) SetIpv4Address(v string) {
	o.Ipv4Address = v
}

// GetAddedRecordsCount returns the AddedRecordsCount field value
func (o *ConnectorRunLogs) GetAddedRecordsCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AddedRecordsCount
}

// GetAddedRecordsCountOk returns a tuple with the AddedRecordsCount field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogs) GetAddedRecordsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AddedRecordsCount, true
}

// SetAddedRecordsCount sets field value
func (o *ConnectorRunLogs) SetAddedRecordsCount(v int32) {
	o.AddedRecordsCount = v
}

// GetUpdatedRecordsCount returns the UpdatedRecordsCount field value
func (o *ConnectorRunLogs) GetUpdatedRecordsCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UpdatedRecordsCount
}

// GetUpdatedRecordsCountOk returns a tuple with the UpdatedRecordsCount field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogs) GetUpdatedRecordsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedRecordsCount, true
}

// SetUpdatedRecordsCount sets field value
func (o *ConnectorRunLogs) SetUpdatedRecordsCount(v int32) {
	o.UpdatedRecordsCount = v
}

// GetSkippedRecordsCount returns the SkippedRecordsCount field value
func (o *ConnectorRunLogs) GetSkippedRecordsCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SkippedRecordsCount
}

// GetSkippedRecordsCountOk returns a tuple with the SkippedRecordsCount field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogs) GetSkippedRecordsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SkippedRecordsCount, true
}

// SetSkippedRecordsCount sets field value
func (o *ConnectorRunLogs) SetSkippedRecordsCount(v int32) {
	o.SkippedRecordsCount = v
}

// GetErrorLogsCount returns the ErrorLogsCount field value
func (o *ConnectorRunLogs) GetErrorLogsCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ErrorLogsCount
}

// GetErrorLogsCountOk returns a tuple with the ErrorLogsCount field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogs) GetErrorLogsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorLogsCount, true
}

// SetErrorLogsCount sets field value
func (o *ConnectorRunLogs) SetErrorLogsCount(v int32) {
	o.ErrorLogsCount = v
}

func (o ConnectorRunLogs) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["portion_id"] = o.PortionId
	}
	if true {
		toSerialize["portion_correlation_id"] = o.PortionCorrelationId
	}
	if true {
		toSerialize["start_time"] = o.StartTime
	}
	if true {
		toSerialize["end_time"] = o.EndTime
	}
	if true {
		toSerialize["connector"] = o.Connector
	}
	if true {
		toSerialize["is_media_storage_service"] = o.IsMediaStorageService
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["test_run"] = o.TestRun
	}
	if true {
		toSerialize["deployment"] = o.Deployment
	}
	if true {
		toSerialize["ipv4_address"] = o.Ipv4Address
	}
	if true {
		toSerialize["added_records_count"] = o.AddedRecordsCount
	}
	if true {
		toSerialize["updated_records_count"] = o.UpdatedRecordsCount
	}
	if true {
		toSerialize["skipped_records_count"] = o.SkippedRecordsCount
	}
	if true {
		toSerialize["error_logs_count"] = o.ErrorLogsCount
	}
	return json.Marshal(toSerialize)
}

type NullableConnectorRunLogs struct {
	value *ConnectorRunLogs
	isSet bool
}

func (v NullableConnectorRunLogs) Get() *ConnectorRunLogs {
	return v.value
}

func (v *NullableConnectorRunLogs) Set(val *ConnectorRunLogs) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorRunLogs) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorRunLogs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorRunLogs(val *ConnectorRunLogs) *NullableConnectorRunLogs {
	return &NullableConnectorRunLogs{value: val, isSet: true}
}

func (v NullableConnectorRunLogs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorRunLogs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


