/*
External API

## Date type fields API endpoints expected date in UTC±0:00 timezone. Timezones in ISO8601 format will be ignored. API endpoints support date in two formats (one of): ISO8601 ('YYYY-MM-DDTHH:mm:SSZ') or Unix Timestamp (seconds count since January 1st, 1970 at UTC).  ## Dropdown fields Some fields are configured as dropdown fields with a dedicated list of values within Oomnitza. You can review the list of available dropdown values within the customization page in Oomnitza. In case you want to be able to post any data into these fields, you should switch them to dropdown without value within the customization page. 

API version: 3.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UsersSaaSRoleUpdateListObjectRolesInner struct for UsersSaaSRoleUpdateListObjectRolesInner
type UsersSaaSRoleUpdateListObjectRolesInner struct {
	RoleExternalId string `json:"role_external_id"`
	RoleExternalLabel *string `json:"role_external_label,omitempty"`
}

// NewUsersSaaSRoleUpdateListObjectRolesInner instantiates a new UsersSaaSRoleUpdateListObjectRolesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersSaaSRoleUpdateListObjectRolesInner(roleExternalId string) *UsersSaaSRoleUpdateListObjectRolesInner {
	this := UsersSaaSRoleUpdateListObjectRolesInner{}
	this.RoleExternalId = roleExternalId
	return &this
}

// NewUsersSaaSRoleUpdateListObjectRolesInnerWithDefaults instantiates a new UsersSaaSRoleUpdateListObjectRolesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersSaaSRoleUpdateListObjectRolesInnerWithDefaults() *UsersSaaSRoleUpdateListObjectRolesInner {
	this := UsersSaaSRoleUpdateListObjectRolesInner{}
	return &this
}

// GetRoleExternalId returns the RoleExternalId field value
func (o *UsersSaaSRoleUpdateListObjectRolesInner) GetRoleExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleExternalId
}

// GetRoleExternalIdOk returns a tuple with the RoleExternalId field value
// and a boolean to check if the value has been set.
func (o *UsersSaaSRoleUpdateListObjectRolesInner) GetRoleExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleExternalId, true
}

// SetRoleExternalId sets field value
func (o *UsersSaaSRoleUpdateListObjectRolesInner) SetRoleExternalId(v string) {
	o.RoleExternalId = v
}

// GetRoleExternalLabel returns the RoleExternalLabel field value if set, zero value otherwise.
func (o *UsersSaaSRoleUpdateListObjectRolesInner) GetRoleExternalLabel() string {
	if o == nil || o.RoleExternalLabel == nil {
		var ret string
		return ret
	}
	return *o.RoleExternalLabel
}

// GetRoleExternalLabelOk returns a tuple with the RoleExternalLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersSaaSRoleUpdateListObjectRolesInner) GetRoleExternalLabelOk() (*string, bool) {
	if o == nil || o.RoleExternalLabel == nil {
		return nil, false
	}
	return o.RoleExternalLabel, true
}

// HasRoleExternalLabel returns a boolean if a field has been set.
func (o *UsersSaaSRoleUpdateListObjectRolesInner) HasRoleExternalLabel() bool {
	if o != nil && o.RoleExternalLabel != nil {
		return true
	}

	return false
}

// SetRoleExternalLabel gets a reference to the given string and assigns it to the RoleExternalLabel field.
func (o *UsersSaaSRoleUpdateListObjectRolesInner) SetRoleExternalLabel(v string) {
	o.RoleExternalLabel = &v
}

func (o UsersSaaSRoleUpdateListObjectRolesInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["role_external_id"] = o.RoleExternalId
	}
	if o.RoleExternalLabel != nil {
		toSerialize["role_external_label"] = o.RoleExternalLabel
	}
	return json.Marshal(toSerialize)
}

type NullableUsersSaaSRoleUpdateListObjectRolesInner struct {
	value *UsersSaaSRoleUpdateListObjectRolesInner
	isSet bool
}

func (v NullableUsersSaaSRoleUpdateListObjectRolesInner) Get() *UsersSaaSRoleUpdateListObjectRolesInner {
	return v.value
}

func (v *NullableUsersSaaSRoleUpdateListObjectRolesInner) Set(val *UsersSaaSRoleUpdateListObjectRolesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersSaaSRoleUpdateListObjectRolesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersSaaSRoleUpdateListObjectRolesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersSaaSRoleUpdateListObjectRolesInner(val *UsersSaaSRoleUpdateListObjectRolesInner) *NullableUsersSaaSRoleUpdateListObjectRolesInner {
	return &NullableUsersSaaSRoleUpdateListObjectRolesInner{value: val, isSet: true}
}

func (v NullableUsersSaaSRoleUpdateListObjectRolesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersSaaSRoleUpdateListObjectRolesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


