/*
External API

## Date type fields API endpoints expected date in UTC±0:00 timezone. Timezones in ISO8601 format will be ignored. API endpoints support date in two formats (one of): ISO8601 ('YYYY-MM-DDTHH:mm:SSZ') or Unix Timestamp (seconds count since January 1st, 1970 at UTC).  ## Dropdown fields Some fields are configured as dropdown fields with a dedicated list of values within Oomnitza. You can review the list of available dropdown values within the customization page in Oomnitza. In case you want to be able to post any data into these fields, you should switch them to dropdown without value within the customization page. 

API version: 3.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MetadataFieldDependencies struct for MetadataFieldDependencies
type MetadataFieldDependencies struct {
	ExternalId []string `json:"{external_id}"`
}

// NewMetadataFieldDependencies instantiates a new MetadataFieldDependencies object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetadataFieldDependencies(externalId []string) *MetadataFieldDependencies {
	this := MetadataFieldDependencies{}
	this.ExternalId = externalId
	return &this
}

// NewMetadataFieldDependenciesWithDefaults instantiates a new MetadataFieldDependencies object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetadataFieldDependenciesWithDefaults() *MetadataFieldDependencies {
	this := MetadataFieldDependencies{}
	return &this
}

// GetExternalId returns the ExternalId field value
func (o *MetadataFieldDependencies) GetExternalId() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value
// and a boolean to check if the value has been set.
func (o *MetadataFieldDependencies) GetExternalIdOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId, true
}

// SetExternalId sets field value
func (o *MetadataFieldDependencies) SetExternalId(v []string) {
	o.ExternalId = v
}

func (o MetadataFieldDependencies) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["{external_id}"] = o.ExternalId
	}
	return json.Marshal(toSerialize)
}

type NullableMetadataFieldDependencies struct {
	value *MetadataFieldDependencies
	isSet bool
}

func (v NullableMetadataFieldDependencies) Get() *MetadataFieldDependencies {
	return v.value
}

func (v *NullableMetadataFieldDependencies) Set(val *MetadataFieldDependencies) {
	v.value = val
	v.isSet = true
}

func (v NullableMetadataFieldDependencies) IsSet() bool {
	return v.isSet
}

func (v *NullableMetadataFieldDependencies) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetadataFieldDependencies(val *MetadataFieldDependencies) *NullableMetadataFieldDependencies {
	return &NullableMetadataFieldDependencies{value: val, isSet: true}
}

func (v NullableMetadataFieldDependencies) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetadataFieldDependencies) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


