/*
External API

## Date type fields API endpoints expected date in UTC±0:00 timezone. Timezones in ISO8601 format will be ignored. API endpoints support date in two formats (one of): ISO8601 ('YYYY-MM-DDTHH:mm:SSZ') or Unix Timestamp (seconds count since January 1st, 1970 at UTC).  ## Dropdown fields Some fields are configured as dropdown fields with a dedicated list of values within Oomnitza. You can review the list of available dropdown values within the customization page in Oomnitza. In case you want to be able to post any data into these fields, you should switch them to dropdown without value within the customization page. 

API version: 3.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oomnitza

import (
	"encoding/json"
)

// ConnectorRunLogsPortionDetails struct for ConnectorRunLogsPortionDetails
type ConnectorRunLogsPortionDetails struct {
	Connector string `json:"connector"`
	Deployment string `json:"deployment"`
	StartTime int32 `json:"start_time"`
	EndTime int32 `json:"end_time"`
	Status string `json:"status"`
	Ipv4Address string `json:"ipv4_address"`
	Objects ConnectorRunLogsPortionDetailsObjects `json:"objects"`
	Logs ConnectorRunLogsPortionDetailsLogs `json:"logs"`
	FileAttachment NullableConnectorRunLogsPortionDetailsFileAttachment `json:"file_attachment"`
	TestRun bool `json:"test_run"`
	TestRunPayload []map[string]interface{} `json:"test_run_payload"`
}

// NewConnectorRunLogsPortionDetails instantiates a new ConnectorRunLogsPortionDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorRunLogsPortionDetails(connector string, deployment string, startTime int32, endTime int32, status string, ipv4Address string, objects ConnectorRunLogsPortionDetailsObjects, logs ConnectorRunLogsPortionDetailsLogs, fileAttachment NullableConnectorRunLogsPortionDetailsFileAttachment, testRun bool, testRunPayload []map[string]interface{}) *ConnectorRunLogsPortionDetails {
	this := ConnectorRunLogsPortionDetails{}
	this.Connector = connector
	this.Deployment = deployment
	this.StartTime = startTime
	this.EndTime = endTime
	this.Status = status
	this.Ipv4Address = ipv4Address
	this.Objects = objects
	this.Logs = logs
	this.FileAttachment = fileAttachment
	this.TestRun = testRun
	this.TestRunPayload = testRunPayload
	return &this
}

// NewConnectorRunLogsPortionDetailsWithDefaults instantiates a new ConnectorRunLogsPortionDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorRunLogsPortionDetailsWithDefaults() *ConnectorRunLogsPortionDetails {
	this := ConnectorRunLogsPortionDetails{}
	return &this
}

// GetConnector returns the Connector field value
func (o *ConnectorRunLogsPortionDetails) GetConnector() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Connector
}

// GetConnectorOk returns a tuple with the Connector field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogsPortionDetails) GetConnectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Connector, true
}

// SetConnector sets field value
func (o *ConnectorRunLogsPortionDetails) SetConnector(v string) {
	o.Connector = v
}

// GetDeployment returns the Deployment field value
func (o *ConnectorRunLogsPortionDetails) GetDeployment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Deployment
}

// GetDeploymentOk returns a tuple with the Deployment field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogsPortionDetails) GetDeploymentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deployment, true
}

// SetDeployment sets field value
func (o *ConnectorRunLogsPortionDetails) SetDeployment(v string) {
	o.Deployment = v
}

// GetStartTime returns the StartTime field value
func (o *ConnectorRunLogsPortionDetails) GetStartTime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogsPortionDetails) GetStartTimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *ConnectorRunLogsPortionDetails) SetStartTime(v int32) {
	o.StartTime = v
}

// GetEndTime returns the EndTime field value
func (o *ConnectorRunLogsPortionDetails) GetEndTime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogsPortionDetails) GetEndTimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *ConnectorRunLogsPortionDetails) SetEndTime(v int32) {
	o.EndTime = v
}

// GetStatus returns the Status field value
func (o *ConnectorRunLogsPortionDetails) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogsPortionDetails) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ConnectorRunLogsPortionDetails) SetStatus(v string) {
	o.Status = v
}

// GetIpv4Address returns the Ipv4Address field value
func (o *ConnectorRunLogsPortionDetails) GetIpv4Address() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ipv4Address
}

// GetIpv4AddressOk returns a tuple with the Ipv4Address field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogsPortionDetails) GetIpv4AddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ipv4Address, true
}

// SetIpv4Address sets field value
func (o *ConnectorRunLogsPortionDetails) SetIpv4Address(v string) {
	o.Ipv4Address = v
}

// GetObjects returns the Objects field value
func (o *ConnectorRunLogsPortionDetails) GetObjects() ConnectorRunLogsPortionDetailsObjects {
	if o == nil {
		var ret ConnectorRunLogsPortionDetailsObjects
		return ret
	}

	return o.Objects
}

// GetObjectsOk returns a tuple with the Objects field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogsPortionDetails) GetObjectsOk() (*ConnectorRunLogsPortionDetailsObjects, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Objects, true
}

// SetObjects sets field value
func (o *ConnectorRunLogsPortionDetails) SetObjects(v ConnectorRunLogsPortionDetailsObjects) {
	o.Objects = v
}

// GetLogs returns the Logs field value
func (o *ConnectorRunLogsPortionDetails) GetLogs() ConnectorRunLogsPortionDetailsLogs {
	if o == nil {
		var ret ConnectorRunLogsPortionDetailsLogs
		return ret
	}

	return o.Logs
}

// GetLogsOk returns a tuple with the Logs field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogsPortionDetails) GetLogsOk() (*ConnectorRunLogsPortionDetailsLogs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Logs, true
}

// SetLogs sets field value
func (o *ConnectorRunLogsPortionDetails) SetLogs(v ConnectorRunLogsPortionDetailsLogs) {
	o.Logs = v
}

// GetFileAttachment returns the FileAttachment field value
// If the value is explicit nil, the zero value for ConnectorRunLogsPortionDetailsFileAttachment will be returned
func (o *ConnectorRunLogsPortionDetails) GetFileAttachment() ConnectorRunLogsPortionDetailsFileAttachment {
	if o == nil || o.FileAttachment.Get() == nil {
		var ret ConnectorRunLogsPortionDetailsFileAttachment
		return ret
	}

	return *o.FileAttachment.Get()
}

// GetFileAttachmentOk returns a tuple with the FileAttachment field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorRunLogsPortionDetails) GetFileAttachmentOk() (*ConnectorRunLogsPortionDetailsFileAttachment, bool) {
	if o == nil {
		return nil, false
	}
	return o.FileAttachment.Get(), o.FileAttachment.IsSet()
}

// SetFileAttachment sets field value
func (o *ConnectorRunLogsPortionDetails) SetFileAttachment(v ConnectorRunLogsPortionDetailsFileAttachment) {
	o.FileAttachment.Set(&v)
}

// GetTestRun returns the TestRun field value
func (o *ConnectorRunLogsPortionDetails) GetTestRun() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TestRun
}

// GetTestRunOk returns a tuple with the TestRun field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogsPortionDetails) GetTestRunOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TestRun, true
}

// SetTestRun sets field value
func (o *ConnectorRunLogsPortionDetails) SetTestRun(v bool) {
	o.TestRun = v
}

// GetTestRunPayload returns the TestRunPayload field value
func (o *ConnectorRunLogsPortionDetails) GetTestRunPayload() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.TestRunPayload
}

// GetTestRunPayloadOk returns a tuple with the TestRunPayload field value
// and a boolean to check if the value has been set.
func (o *ConnectorRunLogsPortionDetails) GetTestRunPayloadOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.TestRunPayload, true
}

// SetTestRunPayload sets field value
func (o *ConnectorRunLogsPortionDetails) SetTestRunPayload(v []map[string]interface{}) {
	o.TestRunPayload = v
}

func (o ConnectorRunLogsPortionDetails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["connector"] = o.Connector
	}
	if true {
		toSerialize["deployment"] = o.Deployment
	}
	if true {
		toSerialize["start_time"] = o.StartTime
	}
	if true {
		toSerialize["end_time"] = o.EndTime
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["ipv4_address"] = o.Ipv4Address
	}
	if true {
		toSerialize["objects"] = o.Objects
	}
	if true {
		toSerialize["logs"] = o.Logs
	}
	if true {
		toSerialize["file_attachment"] = o.FileAttachment.Get()
	}
	if true {
		toSerialize["test_run"] = o.TestRun
	}
	if true {
		toSerialize["test_run_payload"] = o.TestRunPayload
	}
	return json.Marshal(toSerialize)
}

type NullableConnectorRunLogsPortionDetails struct {
	value *ConnectorRunLogsPortionDetails
	isSet bool
}

func (v NullableConnectorRunLogsPortionDetails) Get() *ConnectorRunLogsPortionDetails {
	return v.value
}

func (v *NullableConnectorRunLogsPortionDetails) Set(val *ConnectorRunLogsPortionDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorRunLogsPortionDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorRunLogsPortionDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorRunLogsPortionDetails(val *ConnectorRunLogsPortionDetails) *NullableConnectorRunLogsPortionDetails {
	return &NullableConnectorRunLogsPortionDetails{value: val, isSet: true}
}

func (v NullableConnectorRunLogsPortionDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorRunLogsPortionDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


